# Generated by Django 3.2.8 on 2021-10-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20211022_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diary')),
            ],
        ),
    ]
