# Generated by Django 3.2.8 on 2021-10-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diary_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary_note',
            name='created',
        ),
    ]
