# Generated by Django 3.2.8 on 2021-10-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20211023_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_note',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
