# Generated by Django 3.2.8 on 2021-10-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diary_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary_note',
            name='image',
        ),
    ]
